### ISSUE TITLE
Invoke-ScriptAnalyzer always sets the exit code to 0 (even when the analyzer finds problems)

### ISSUE THREAD

**Issue by Ian-Rowland-i2** [CircleCI-Public/microsoft-psscriptanalyzer-orb#4]
## Describe Request:
When using this orb to analyze PowerShell scripts in private orbs, when problems are reported, the [check](https://circleci.com/developer/orbs/orb/circleci/microsoft-psscriptanalyzer#commands-check) command always returns an exit code of '0', causing the job to succeed, when we want it to fail. 

This requires having to inspect each orb build to see if errors are being reported.

When developing orbs that contain PowerShell scripts, the build should fail if problems are found.

Adding an additional parameter `-EnableExit` to the call to `Invoke-ScriptAnalyzer`  returns an exit code equal to the number of error records causing the build to go red. This can be useful in continuous integration (CI) pipelines too (not just with private orbs).

The switch could be made optional, for backwards compatibility.

## Supporting Documentation Links:
https://learn.microsoft.com/en-us/powershell/module/psscriptanalyzer/invoke-scriptanalyzer?view=ps-modules#-enableexit

**Comment by nathanfishcircleci** [comment]
This specific orb is no longer supported.
